// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  productSidebar: [{type: 'autogenerated', dirName: 'product'}],
  architectureSidebar: [{type: 'autogenerated', dirName: 'architecture'}],
  engineeringSidebar: [{type: 'autogenerated', dirName: 'engineering'}],
};

export default sidebars;
